config/routes.rb
Depot::Application.routes.draw do
  

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end
  
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, :on => :member
    end
    root :to => "store#index", :as => 'store'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= raw stylesheet_link_merged :base %>
  <%= raw javascript_include_merged :base %>
  <%= csrf_meta_tag %>
</head>
<body id="store">
  <div id="banner">
    <%= form_tag store_path, :class => 'locale' do %>
      <%= select_tag 'set_locale', 
        options_for_select(LANGUAGES, I18n.locale.to_s),
          :onchange => 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%#= javascript_tag "$$('.locale input').each(Element.hide)" %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %>
    
    <%= link_to image_tag("logo.png"), store_path %>
    <%= @page_title || t('.title') %>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
          <%= render @cart %>
        <% end %>
      <% end %>
      <a href=""></a><br />
      <a href=""><%= t('.home') %></a><br />
      <a href=""><%= t('.question') %></a><br />
      <a href=""><%= t('.news') %></a><br />
      <a href=""><%= t('.contact') %></a><br />
      
      <% if session[:user_id] %>
        <br />
        <%= link_to 'Orders', orders_path %><br />
        <%= link_to 'Products', products_path%><br />
        <%= link_to 'Users', users_path %><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete %><br />
      <% end %>
      <p><span id="timer">Current time is <%= Time.now %></span></p>
      <p><span id="Counter">Total <%=pluralize(session[:counter], 'visitor') %>.</span></p>
      
        
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>
</html>